name = "svelte-world-conflict-websocket"
main = "src/index.js"
compatibility_date = "2024-05-15"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
    { name = "WEBSOCKET_HIBERNATION_SERVER", class_name = "WebSocketHibernationServer" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebSocketHibernationServer"]