name = "svelte-world-conflict-websocket"
main = "src/index.js"
compatibility_date = "2024-05-15"

[durable_objects]
bindings = [
    { name = "WEBSOCKET_HIBERNATION_SERVER", class_name = "WebSocketHibernationServer" }
]

[[durable_objects.migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]
